package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.summ.debook.type.Authority;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import java.util.Objects;

/**
 * AuthoritiesIdEntity generated by hbm2java
 */
@Embeddable
public class AuthoritiesIdEntity implements java.io.Serializable {

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "authority", nullable = false, length = 45)
    private Authority authority;

    public AuthoritiesIdEntity() {
    }

    public AuthoritiesIdEntity(Long userId, Authority authority) {
        this.userId = userId;
        this.authority = authority;
    }

    public Long getUserId() {
        return this.userId;
    }

    public Authority getAuthority() {
        return this.authority;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AuthoritiesIdEntity that = (AuthoritiesIdEntity) o;
        return Objects.equals(userId, that.userId) &&
                authority == that.authority;
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, authority);
    }
}
