package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.summ.debook.type.Authority;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AuthoritiesEntity generated by hbm2java
 */
@Entity
@Table(name = "authorities",
        uniqueConstraints = @UniqueConstraint(columnNames = { "user_id", "authority" }) )
public class AuthoritiesEntity implements java.io.Serializable {

    @EmbeddedId
    private AuthoritiesIdEntity id;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private UserEntity user;

    public AuthoritiesEntity() {
    }

    public AuthoritiesEntity(Authority authority, UserEntity user) {
        if (user.getUserId() == null) {
            throw new IllegalStateException("User is transient: " + user);
        }
        this.id = new AuthoritiesIdEntity(user.getUserId(), authority);
        this.user = user;
    }

    public AuthoritiesIdEntity getId() {
        return this.id;
    }

    public UserEntity getUser() {
        return this.user;
    }
}
