package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AuthoritiesEntity generated by hbm2java
 */
@Entity
@Table(name = "authorities", catalog = "debook_db", uniqueConstraints = @UniqueConstraint(columnNames = { "user_id",
        "authority" }) )
public class AuthoritiesEntity implements java.io.Serializable {

    private AuthoritiesIdEntity id;
    private UserEntity user;

    public AuthoritiesEntity() {
    }

    public AuthoritiesEntity(AuthoritiesIdEntity id, UserEntity user) {
        this.id = id;
        this.user = user;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false) ),
            @AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false, length = 45) ) })
    public AuthoritiesIdEntity getId() {
        return this.id;
    }

    public void setId(AuthoritiesIdEntity id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public UserEntity getUser() {
        return this.user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

}
