package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.summ.debook.type.Authority;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import java.util.Objects;

/**
 * AuthoritiesIdEntity generated by hbm2java
 */
@Embeddable
public class AuthoritiesIdEntity implements java.io.Serializable {

    @Column(name = "user_id", nullable = false)
    private Long userId;
    @Column(name = "authority", nullable = false, length = 45)
    @Enumerated(EnumType.STRING)
    private Authority authority;

    public AuthoritiesIdEntity() {
    }

    public AuthoritiesIdEntity(Long userId, Authority authority) {
        this.userId = userId;
        this.authority = authority;
    }

    public Long getUserId() {
        return this.userId;
    }

    public Authority getAuthority() {
        return this.authority;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AuthoritiesIdEntity))
            return false;
        AuthoritiesIdEntity castOther = (AuthoritiesIdEntity) other;

        return (this.getUserId() == castOther.getUserId())
                && ((this.getAuthority() == castOther.getAuthority()) || (this.getAuthority() != null
                        && castOther.getAuthority() != null && this.getAuthority().equals(castOther.getAuthority())));
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, authority);
    }
}
