package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.summ.debook.type.CreditType;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * CreditTypeEntity generated by hbm2java
 */
@Entity
@Table(name = "credit_type")
public class CreditTypeEntity implements java.io.Serializable {

    @JsonIgnore
    @Id
    @Column(name = "credit_type_id", unique = true, nullable = false)
    private Long creditTypeId;

    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 45)
    private CreditType type;

    public CreditTypeEntity() {
    }

    public CreditTypeEntity(Long creditTypeId, CreditType type) {
        this.creditTypeId = creditTypeId;
        this.type = type;
    }

    public Long getCreditTypeId() {
        return this.creditTypeId;
    }

    public void setCreditTypeId(Long creditTypeId) {
        this.creditTypeId = creditTypeId;
    }

    public CreditType getType() {
        return this.type;
    }

    public void setType(CreditType type) {
        this.type = type;
    }

}
