package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CreditTypeEntity generated by hbm2java
 */
@Entity
@Table(name = "credit_type", catalog = "debook_db")
public class CreditTypeEntity implements java.io.Serializable {

    @JsonIgnore
    private int creditTypeId;
    private String type;

    public CreditTypeEntity() {
    }

    public CreditTypeEntity(int creditTypeId, String type) {
        this.creditTypeId = creditTypeId;
        this.type = type;
    }

    @Id
    @Column(name = "credit_type_id", unique = true, nullable = false)
    public int getCreditTypeId() {
        return this.creditTypeId;
    }

    public void setCreditTypeId(int creditTypeId) {
        this.creditTypeId = creditTypeId;
    }

    @Column(name = "type", nullable = false, length = 45)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
