package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CurrencyEntity generated by hbm2java
 */
@Entity
@Table(name = "currency", catalog = "debook_db")
public class CurrencyEntity implements java.io.Serializable {

    @JsonIgnore
    private int currencyId;
    private String code;
    private String sign;

    public CurrencyEntity() {
    }

    public CurrencyEntity(int currencyId, String code, String sign) {
        this.currencyId = currencyId;
        this.code = code;
        this.sign = sign;
    }

    @Id
    @Column(name = "currency_id", unique = true, nullable = false)
    public int getCurrencyId() {
        return this.currencyId;
    }

    public void setCurrencyId(int currencyId) {
        this.currencyId = currencyId;
    }

    @Column(name = "code", nullable = false, length = 45)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "sign", nullable = false, length = 45)
    public String getSign() {
        return this.sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

}
