package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CurrencyEntity generated by hbm2java
 */
@Entity
@Table(name = "currency")
public class CurrencyEntity implements java.io.Serializable {

    private Long id;
    private String code;
    private String sign;

    public CurrencyEntity() {
    }

    public CurrencyEntity(Long id, String code, String sign) {
        this.id = id;
        this.code = code;
        this.sign = sign;
    }

    @Id
    @Column(name = "currency_id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "code", nullable = false, length = 45)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "sign", nullable = false, length = 45)
    public String getSign() {
        return this.sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

}
