package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DebtEntity generated by hbm2java
 */
@Entity
@Table(name = "debt", catalog = "debook_db")
public class DebtEntity implements java.io.Serializable {

    private DebtIdEntity id;
    private CurrencyEntity currency;
    private UserEntity userByCreditorUserId;
    private UserEntity userByDebtorUserId;
    private BigDecimal value;

    public DebtEntity() {
    }

    public DebtEntity(DebtIdEntity id, CurrencyEntity currency, UserEntity userByCreditorUserId, UserEntity userByDebtorUserId, BigDecimal value) {
        this.id = id;
        this.currency = currency;
        this.userByCreditorUserId = userByCreditorUserId;
        this.userByDebtorUserId = userByDebtorUserId;
        this.value = value;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "debtorUserId", column = @Column(name = "debtor_user_id", nullable = false) ),
            @AttributeOverride(name = "creditorUserId", column = @Column(name = "creditor_user_id", nullable = false) ),
            @AttributeOverride(name = "currencyId", column = @Column(name = "currency_id", nullable = false) ) })
    public DebtIdEntity getId() {
        return this.id;
    }

    public void setId(DebtIdEntity id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "currency_id", nullable = false, insertable = false, updatable = false)
    public CurrencyEntity getCurrency() {
        return this.currency;
    }

    public void setCurrency(CurrencyEntity currency) {
        this.currency = currency;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "creditor_user_id", nullable = false, insertable = false, updatable = false)
    public UserEntity getUserByCreditorUserId() {
        return this.userByCreditorUserId;
    }

    public void setUserByCreditorUserId(UserEntity userByCreditorUserId) {
        this.userByCreditorUserId = userByCreditorUserId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "debtor_user_id", nullable = false, insertable = false, updatable = false)
    public UserEntity getUserByDebtorUserId() {
        return this.userByDebtorUserId;
    }

    public void setUserByDebtorUserId(UserEntity userByDebtorUserId) {
        this.userByDebtorUserId = userByDebtorUserId;
    }

    @Column(name = "value", nullable = false, precision = 15)
    public BigDecimal getValue() {
        return this.value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

}
