package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Objects;
import javax.persistence.*;

/**
 * DebtEntity generated by hbm2java
 */
@Entity
@Table(name = "debt")
public class DebtEntity implements java.io.Serializable {

    @JsonIgnore
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "debt_id", unique = true, nullable = false)
    private Long id;

    @JsonBackReference
    @ManyToOne()
    @JoinColumn(name = "person_id", nullable = false, updatable = false)
    private PersonEntity person;

    @ManyToOne
    @JoinColumn(name = "currency_id", nullable = false, updatable = false)
    private CurrencyEntity currency;

    @ManyToOne
    @JoinColumn(name = "credit_type_id", nullable = false)
    private CreditTypeEntity creditType;

    @Column(name = "value", nullable = false, precision = 15)
    private BigDecimal value;

    @JsonIgnore
    @CreationTimestamp
    @Column(name = "create_time")
    protected Timestamp createTime;

    @JsonIgnore
    @UpdateTimestamp
    @Column(name = "update_time")
    protected Timestamp updateTime;

    public DebtEntity() {
    }

    public DebtEntity(Long id, UserEntity user, PersonEntity person, CurrencyEntity currency,
                      CreditTypeEntity creditType, BigDecimal value) {
        this.id = id;
        this.person = person;
        this.currency = currency;
        this.creditType = creditType;
        this.value = value;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public PersonEntity getPerson() {
        return this.person;
    }

    public void setPerson(PersonEntity person) {
        this.person = person;
    }

    public CurrencyEntity getCurrency() {
        return this.currency;
    }

    public void setCurrency(CurrencyEntity currency) {
        this.currency = currency;
    }

    public CreditTypeEntity getCreditType() {
        return this.creditType;
    }

    public void setCreditType(CreditTypeEntity creditType) {
        this.creditType = creditType;
    }

    public BigDecimal getValue() {
        return this.value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}
