package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Objects;

/**
 * DebtIdEntity generated by hbm2java
 */
@Embeddable
public class DebtIdEntity implements java.io.Serializable {

    @Column(name = "user_id", nullable = false)
    private Long userId;
    @Column(name = "person_id", nullable = false)
    private Long personId;
    @Column(name = "currency_id", nullable = false)
    private Long currencyId;

    public DebtIdEntity() {
    }

    public DebtIdEntity(Long userId, Long personId, Long currencyId) {
        this.userId = userId;
        this.personId = personId;
        this.currencyId = currencyId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getLocalUserId() {
        return this.personId;
    }

    public void setLocalUserId(Long localUserId) {
        this.personId = localUserId;
    }

    @Column(name = "currency_id", nullable = false)
    public Long getCurrencyId() {
        return this.currencyId;
    }

    public void setCurrencyId(Long currencyId) {
        this.currencyId = currencyId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DebtIdEntity that = (DebtIdEntity) o;
        return Objects.equals(userId, that.userId) &&
                Objects.equals(personId, that.personId) &&
                Objects.equals(currencyId, that.currencyId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, personId, currencyId);
    }
}
