package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.math.BigDecimal;
import java.util.Objects;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DebtEntity generated by hbm2java
 */
@Entity
@Table(name = "debt", catalog = "debook_db")
public class DebtEntity implements java.io.Serializable {

    @JsonIgnore
    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false) ),
            @AttributeOverride(name = "personId", column = @Column(name = "person_id", nullable = false) ),
            @AttributeOverride(name = "currencyId", column = @Column(name = "currency_id", nullable = false) )
    })
    private DebtIdEntity id;

    @ManyToOne()
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private UserEntity user;

    @ManyToOne()
    @JoinColumn(name = "person_id", nullable = false, insertable = false, updatable = false)
    private PersonEntity person;

    @ManyToOne
    @JoinColumn(name = "currency_id", nullable = false, insertable = false, updatable = false)
    private CurrencyEntity currency;

    @ManyToOne
    @JoinColumn(name = "credit_type_id", nullable = false)
    private CreditTypeEntity creditType;

    @Column(name = "value", nullable = false, precision = 15)
    private BigDecimal value;

    public DebtEntity() {
    }

    public DebtEntity(DebtIdEntity id, UserEntity user, PersonEntity person, CurrencyEntity currency,
                      CreditTypeEntity creditType, BigDecimal value) {
        this.id = id;
        this.user = user;
        this.person = person;
        this.currency = currency;
        this.creditType = creditType;
        this.value = value;
    }

    public DebtIdEntity getId() {
        return this.id;
    }

    public void setId(DebtIdEntity id) {
        this.id = id;
    }

    public UserEntity getUser() {
        return this.user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

    public PersonEntity getPerson() {
        return this.person;
    }

    public void sePerson(PersonEntity person) {
        this.person = person;
    }

    public CurrencyEntity getCurrency() {
        return this.currency;
    }

    public void setCurrency(CurrencyEntity currency) {
        this.currency = currency;
    }

    public CreditTypeEntity getCreditType() {
        return this.creditType;
    }

    public void setCreditType(CreditTypeEntity creditType) {
        this.creditType = creditType;
    }

    public BigDecimal getValue() {
        return this.value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DebtEntity that = (DebtEntity) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
