package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DebtIdEntity generated by hbm2java
 */
@Embeddable
public class DebtIdEntity implements java.io.Serializable {

    private int debtorUserId;
    private int creditorUserId;
    private int currencyId;

    public DebtIdEntity() {
    }

    public DebtIdEntity(int debtorUserId, int creditorUserId, int currencyId) {
        this.debtorUserId = debtorUserId;
        this.creditorUserId = creditorUserId;
        this.currencyId = currencyId;
    }

    @Column(name = "debtor_user_id", nullable = false)
    public int getDebtorUserId() {
        return this.debtorUserId;
    }

    public void setDebtorUserId(int debtorUserId) {
        this.debtorUserId = debtorUserId;
    }

    @Column(name = "creditor_user_id", nullable = false)
    public int getCreditorUserId() {
        return this.creditorUserId;
    }

    public void setCreditorUserId(int creditorUserId) {
        this.creditorUserId = creditorUserId;
    }

    @Column(name = "currency_id", nullable = false)
    public int getCurrencyId() {
        return this.currencyId;
    }

    public void setCurrencyId(int currencyId) {
        this.currencyId = currencyId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof DebtIdEntity))
            return false;
        DebtIdEntity castOther = (DebtIdEntity) other;

        return (this.getDebtorUserId() == castOther.getDebtorUserId())
                && (this.getCreditorUserId() == castOther.getCreditorUserId())
                && (this.getCurrencyId() == castOther.getCurrencyId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getDebtorUserId();
        result = 37 * result + this.getCreditorUserId();
        result = 37 * result + this.getCurrencyId();
        return result;
    }

}
