package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LocalUserEntity generated by hbm2java
 */
@Entity
@Table(name = "local_user", catalog = "debook_db", uniqueConstraints = @UniqueConstraint(columnNames = { "user_id",
        "name", "surname" }) )
public class LocalUserEntity implements java.io.Serializable {

    @JsonIgnore
    private Integer localUserId;
    @JsonIgnore
    private UserEntity user;
    private String name;
    private String surname;
    @JsonIgnore
    private Set<LocalDebtEntity> localDebts = new HashSet<LocalDebtEntity>(0);

    public LocalUserEntity() {
    }

    public LocalUserEntity(UserEntity user, String name) {
        this.user = user;
        this.name = name;
    }

    public LocalUserEntity(UserEntity user, String name, String surname, Set<LocalDebtEntity> localDebts) {
        this.user = user;
        this.name = name;
        this.surname = surname;
        this.localDebts = localDebts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "local_user_id", unique = true, nullable = false)
    public Integer getLocalUserId() {
        return this.localUserId;
    }

    public void setLocalUserId(Integer localUserId) {
        this.localUserId = localUserId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    public UserEntity getUser() {
        return this.user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "surname", length = 45)
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "localUser")
    public Set<LocalDebtEntity> getLocalDebts() {
        return this.localDebts;
    }

    public void setLocalDebts(Set<LocalDebtEntity> localDebts) {
        this.localDebts = localDebts;
    }

}
