package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LocalDebtEntity generated by hbm2java
 */
@Entity
@Table(name = "local_debt", catalog = "debook_db")
public class LocalDebtEntity implements java.io.Serializable {

    @JsonIgnore
    private LocalDebtIdEntity id;
    private CreditTypeEntity creditType;
    private CurrencyEntity currency;
    private LocalUserEntity localUser;
    private UserEntity user;
    private BigDecimal value;

    public LocalDebtEntity() {
    }

    public LocalDebtEntity(LocalDebtIdEntity id, CreditTypeEntity creditType, CurrencyEntity currency, LocalUserEntity localUser, UserEntity user,
                           BigDecimal value) {
        this.id = id;
        this.creditType = creditType;
        this.currency = currency;
        this.localUser = localUser;
        this.user = user;
        this.value = value;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false) ),
            @AttributeOverride(name = "currencyId", column = @Column(name = "currency_id", nullable = false) ),
            @AttributeOverride(name = "localUserId", column = @Column(name = "local_user_id", nullable = false) ) })
    public LocalDebtIdEntity getId() {
        return this.id;
    }

    public void setId(LocalDebtIdEntity id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "credit_type_id", nullable = false)
    public CreditTypeEntity getCreditType() {
        return this.creditType;
    }

    public void setCreditType(CreditTypeEntity creditType) {
        this.creditType = creditType;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "currency_id", nullable = false, insertable = false, updatable = false)
    public CurrencyEntity getCurrency() {
        return this.currency;
    }

    public void setCurrency(CurrencyEntity currency) {
        this.currency = currency;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "local_user_id", nullable = false, insertable = false, updatable = false)
    public LocalUserEntity getLocalUser() {
        return this.localUser;
    }

    public void setLocalUser(LocalUserEntity localUser) {
        this.localUser = localUser;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public UserEntity getUser() {
        return this.user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

    @Column(name = "value", nullable = false, precision = 15)
    public BigDecimal getValue() {
        return this.value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

}
