package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonEntity generated by hbm2java
 */
@Entity
@Table(name = "person")
public class PersonEntity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "person_id", unique = true, nullable = false)
    private Long personId;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "owner_user_id", nullable = false)
    private UserEntity ownerUser;

    @JsonIgnore //TODO TEMP
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "connected_user_id")
    private UserEntity connectedUser;

    @JsonIgnore //TODO TEMP
    @Column(name = "connection_approved")
    private Boolean connectionApproved;

    @Column(name = "name", nullable = false, length = 45)
    private String name;

    @Column(name = "surname", length = 45)
    private String surname;

    @JsonManagedReference
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "person")
    private List<DebtEntity> debts = new ArrayList<>(0);

    @JsonIgnore
    @CreationTimestamp
    @Column(name = "create_time")
    protected Timestamp createTime;

    @JsonIgnore
    @UpdateTimestamp
    @Column(name = "update_time")
    protected Timestamp updateTime;

    public PersonEntity() {
    }

    public PersonEntity(UserEntity ownerUser, String name) {
        this.ownerUser = ownerUser;
        this.name = name;
    }

    public PersonEntity(UserEntity ownerUser, UserEntity connectedUser, String name, String surname, List<DebtEntity> debts) {
        this.ownerUser = ownerUser;
        this.connectedUser = connectedUser;
        this.name = name;
        this.surname = surname;
        this.debts = debts;
    }

    public Long getPersonId() {
        return personId;
    }

    public UserEntity getOwnerUser() {
        return this.ownerUser;
    }

    public void setOwnerUser(UserEntity ownerUser) {
        this.ownerUser = ownerUser;
    }

    public UserEntity getConnectedUser() {
        return this.connectedUser;
    }

    public void setConnectedUser(UserEntity linkedUser) {
        this.connectedUser = linkedUser;
    }

    public Boolean getConnectionApproved() {
        return connectionApproved;
    }

    public void setConnectionApproved(Boolean connectionApproved) {
        this.connectionApproved = connectionApproved;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public List<DebtEntity> getDebts() {
        return debts;
    }

    public void setDebts(List<DebtEntity> debts) {
        this.debts = debts;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}
