package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PersonEntity generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "debook_db")
public class PersonEntity implements java.io.Serializable {

    @JsonIgnore
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "person_id", unique = true, nullable = false)
    private Long personId;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "owner_user_id", nullable = false)
    private UserEntity ownerUser;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "linked_user_id", nullable = false)
    private UserEntity linkedUser;

    @Column(name = "name", nullable = false, length = 45)
    private String name;

    @Column(name = "surname", length = 45)
    private String surname;

    public PersonEntity() {
    }

    public PersonEntity(UserEntity ownerUser, String name) {
        this.ownerUser = ownerUser;
        this.name = name;
    }

    public PersonEntity(UserEntity ownerUser, UserEntity linkedUser, String name, String surname) {
        this.ownerUser = ownerUser;
        this.linkedUser = linkedUser;
        this.name = name;
        this.surname = surname;
    }

    public UserEntity getOwnerUser() {
        return this.ownerUser;
    }

    public void setOwnerUser(UserEntity ownerUser) {
        this.ownerUser = ownerUser;
    }

    public UserEntity getLinkedUser() {
        return this.linkedUser;
    }

    public void setLinkedUser(UserEntity linkedUser) {
        this.linkedUser = linkedUser;
    }


    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }
}
