package com.summ.debook.entity;
// Generated Jan 23, 2016 2:48:02 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserSecretEntity generated by hbm2java
 */
@Entity
@Table(name = "user_secret")
public class UserSecretEntity implements java.io.Serializable {

    private Long userId;
    private String hash;

    public UserSecretEntity() {
    }

    public UserSecretEntity(Long userId, String hash) {
        this.userId = userId;
        this.hash = hash;
    }

    @Id
    @Column(name = "user_id", unique = true, nullable = false)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "hash", nullable = false, length = 45)
    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

}
