-- MySQL Script generated by MySQL Workbench
-- 04/08/18 16:44:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema debook_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema debook_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `debook_db` DEFAULT CHARACTER SET utf8 ;
USE `debook_db` ;

-- -----------------------------------------------------
-- Table `debook_db`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`currency` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`currency` (
  `currency_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `sign` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`currency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`user` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `activated` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`person` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `owner_user_id` INT NOT NULL,
  `linked_user_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_persons_linked_users_idx` (`linked_user_id` ASC),
  INDEX `fk_persons_owner_users` (`owner_user_id` ASC),
  CONSTRAINT `fk_persons_owner_users`
    FOREIGN KEY (`owner_user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_linked_users`
    FOREIGN KEY (`linked_user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`credit_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`credit_type` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`credit_type` (
  `credit_type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`credit_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`debt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`debt` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`debt` (
  `user_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `credit_type_id` INT NOT NULL,
  `value` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`user_id`, `person_id`, `currency_id`),
  INDEX `fk_debt_person_idx` (`person_id` ASC),
  INDEX `fk_debt_user_idx` (`user_id` ASC),
  INDEX `fk_debt_currency_idx` (`currency_id` ASC),
  INDEX `fk_debt_credit_type_idx` (`credit_type_id` ASC),
  CONSTRAINT `fk_dept_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dept_currency`
    FOREIGN KEY (`person_id`)
    REFERENCES `debook_db`.`currency` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debt_person`
    FOREIGN KEY (`currency_id`)
    REFERENCES `debook_db`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debt_credit_type`
    FOREIGN KEY (`credit_type_id`)
    REFERENCES `debook_db`.`credit_type` (`credit_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`user_secret`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`user_secret` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`user_secret` (
  `user_id` INT NOT NULL,
  `hash` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_secret_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_secret_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`authorities` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`authorities` (
  `user_id` INT NOT NULL,
  `authority` VARCHAR(45) NOT NULL,
  INDEX `fk_authorities_user_idx` (`user_id` ASC),
  UNIQUE INDEX `authorities_user_UNIQUE` (`user_id` ASC, `authority` ASC),
  CONSTRAINT `fk_authorities_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
