-- MySQL Script generated by MySQL Workbench
-- 02/08/16 00:12:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema debook_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema debook_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `debook_db` DEFAULT CHARACTER SET utf8 ;
USE `debook_db` ;

-- -----------------------------------------------------
-- Table `debook_db`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`currency` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`currency` (
  `currency_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(45) NOT NULL COMMENT '',
  `sign` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`currency_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`user` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `surname` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `activated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`debt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`debt` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`debt` (
  `debtor_user_id` INT NOT NULL COMMENT '',
  `creditor_user_id` INT NOT NULL COMMENT '',
  `currency_id` INT NOT NULL COMMENT '',
  `value` DECIMAL(15,2) NOT NULL COMMENT '',
  PRIMARY KEY (`debtor_user_id`, `creditor_user_id`, `currency_id`)  COMMENT '',
  INDEX `fk_debt_user_idx` (`creditor_user_id` ASC)  COMMENT '',
  INDEX `fk_debt_currency_idx` (`currency_id` ASC)  COMMENT '',
  CONSTRAINT `fk_debt_debtor_user`
    FOREIGN KEY (`debtor_user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debt_creditor_user`
    FOREIGN KEY (`creditor_user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debt_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `debook_db`.`currency` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`local_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`local_user` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`local_user` (
  `local_user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `surname` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`local_user_id`)  COMMENT '',
  UNIQUE INDEX `local_user_key_UNIQUE` (`user_id` ASC, `name` ASC, `surname` ASC)  COMMENT '',
  CONSTRAINT `fk_local_users_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`credit_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`credit_type` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`credit_type` (
  `credit_type_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`credit_type_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`local_debt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`local_debt` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`local_debt` (
  `user_id` INT NOT NULL COMMENT '',
  `currency_id` INT NOT NULL COMMENT '',
  `local_user_id` INT NOT NULL COMMENT '',
  `credit_type_id` INT NOT NULL COMMENT '',
  `value` DECIMAL(15,2) NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `currency_id`, `local_user_id`)  COMMENT '',
  INDEX `fk_local_debt_currency_idx` (`currency_id` ASC)  COMMENT '',
  INDEX `fk_local_debt_user_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_local_debt_local_user_idx` (`local_user_id` ASC)  COMMENT '',
  INDEX `fk_local_debt_credit_type_idx` (`credit_type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_local_dept_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_dept_currency`
    FOREIGN KEY (`currency_id`)
    REFERENCES `debook_db`.`currency` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_debt_local_user`
    FOREIGN KEY (`local_user_id`)
    REFERENCES `debook_db`.`local_user` (`local_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_debt_credit_type`
    FOREIGN KEY (`credit_type_id`)
    REFERENCES `debook_db`.`credit_type` (`credit_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`user_secret`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`user_secret` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`user_secret` (
  `user_id` INT NOT NULL COMMENT '',
  `hash` VARCHAR(80) NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  INDEX `fk_users_secret_users_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_secret_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `debook_db`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `debook_db`.`authorities` ;

CREATE TABLE IF NOT EXISTS `debook_db`.`authorities` (
  `user_id` INT NOT NULL COMMENT '',
  `authority` VARCHAR(45) NOT NULL COMMENT '',
  INDEX `fk_authorities_user_idx` (`user_id` ASC)  COMMENT '',
  UNIQUE INDEX `authorities_user_UNIQUE` (`user_id` ASC, `authority` ASC)  COMMENT '',
  CONSTRAINT `fk_authorities_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `debook_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
